### ISSUE TITLE
Form Fields tab has same description as Form Settings

### ISSUE THREAD

**Issue by Mark-H** [Sterc/formalicious#12]
Might be a copy/paste issue ;)

![bug2](https://cloud.githubusercontent.com/assets/312944/7563270/b26b5e74-f7db-11e4-8b31-5a0ec99359ea.jpg)

Form Fields is also disabled before the form is saved first. This makes sense to me as a developer, but maybe you can add a tooltip to the tab or something else to indicate it needs to be saved before you can add fields.

**Comment by MrRoco** [comment]
Change description for Form Fields tab.
