### ISSUE TITLE
Missing label on creating/updating a field in a form

### ISSUE THREAD

**Issue by Mark-H** [Sterc/formalicious#13]
Looks like a lexicon issue. 

![missinglabel](https://cloud.githubusercontent.com/assets/312944/7563349/b7a3350a-f7dc-11e4-9516-288d77280c63.JPG)

**Comment by pixelive** [comment]
Hi Mark,

This should be fixed with the following transport file:

https://github.com/Sterc/formalicious/blob/master/formalicious-0.5.2-beta.transport.zip
