### ISSUE TITLE
How do I add a form that I created to my template?

### ISSUE THREAD

**Issue by DESIGNfromWITHIN** [Sterc/formalicious#4]
No documentation or examples...

**Comment by Bumme** [comment]
Example use with form select TV:

Create a single select tv with input options :  @SELECT '- No form selected -' AS name, 0 AS id UNION ALL SELECT name,id FROM formalicious_forms WHERE published = 1

Put this snippet call inside the template: [-[!renderForm? &form=``]] without the -

**Comment by neoneddy** [comment]
@DESIGNfromWITHIN  Let me know if you get this working.  So far I don't have it sending anything yet.  But I need to test a normal formit form first I think.

**Comment by isaacniebeling** [comment]
@neoneddy You need to make sure all of the individual pieces are published in order to have any output

**Comment by matdave** [comment]
For me I had to add the table prefix to formalicious_forms
