### ISSUE TITLE
Error when using MYSQL 8 

### ISSUE THREAD

**Issue by NatemcM** [Sterc/Formalicious#4]
MYSQL 8 added RANK as a reserved keyword, this is causing issues with methods such as getSteps() when trying to sortby the rank column:

```
$criteria->sortby('rank', 'ASC');
```

To fix we can wrap with ` to pass the keyword.

**Comment by lunardigs** [comment]
I can confirm. If the following three lines are edited to have "rank" wrapped in backticks, Formalicious works properly again.

formaliciousfield.class.php:        $criteria->sortby('rank', 'ASC');
formaliciousform.class.php:        $criteria->sortby('rank', 'ASC');
formaliciousstep.class.php:        $criteria->sortby('rank', 'ASC');

**Comment by 9thwave** [comment]
> I can confirm. If the following three lines are edited to have "rank" wrapped in backticks, Formalicious works properly again.
> 
> formaliciousfield.class.php: $criteria->sortby('rank', 'ASC');
> formaliciousform.class.php: $criteria->sortby('rank', 'ASC');
> formaliciousstep.class.php: $criteria->sortby('rank', 'ASC');

Could you explain where exactly this should go? Thanks.

**Comment by 9thwave** [comment]
Yes this has solved the issue with the **_addition_** of backticks:
$criteria->sortby('`rank`', 'ASC');

**Comment by jenswittmann** [comment]
Is this planed to fix for MODX 2/3? I can add a PR then.

See this: https://github.com/modxcms/xpdo/issues/254#issuecomment-1772665031
