### ISSUE TITLE
[Feature] - Content Blocks Field for forms

### ISSUE THREAD

**Issue by neoneddy** [Sterc/formalicious#5]

**Comment by isaacniebeling** [comment]
This could be done with a snippet field by default, or a chunk field that uses a setting (could use a snippet to get the list of forms and return the IDs as a select setting). Doesn't really need to be its own special field.

**Comment by Bumme** [comment]
@Mark-H Do you accept inline @SELECT bindings?

**Comment by Mark-H** [comment]
No but we do accept snippet calls :)
Op 27 mrt. 2015 10:30 schreef "Wieger Sloot" <notifications@github.com>:

**Comment by Bumme** [comment]
Maybe a nice feature? Just copy paste the code from the modtemplatevar.class.php.
