### ISSUE TITLE
[Feature] - Column  Fields

### ISSUE THREAD

**Issue by neoneddy** [Sterc/formalicious#9]
A way to do multi column layouts, fieldgroups, etc.

**Comment by Bumme** [comment]
You have to do that with html and css. 
Just make your own types with custom tpl's and add them to the form.

**Comment by isaacniebeling** [comment]
@Bumme Are you able to do wrapper-type fields? Basically, I think the need here is for something like a fieldset -- a way of grouping fields together. Ideally, then, that wrapper html would be customizable as well (so fieldsets, divs, sections, or whatever could be used).

**Comment by matdave** [comment]
You code do a field type for start wrapper, and end wrapper.

**Comment by isaacniebeling** [comment]
That seems super hacky and fragile. It'd work, but I don't think I'd trust *clients* to do it.
